[package]
name = "lost_luggage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
search = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5.1"